import uniqid from "uniqid"
import tea from "../assets/image/tea.jpg"
import coffe from "../assets/image/coffee.jpg"
import cola from "../assets/image/cola2.png"
import {BackendState} from "../types/Backend";
export const data: BackendState[] = [
    {
        id: uniqid(),
        name_en: "Tea",
        name_kg: "Чай",
        name_ru: "Чай",
        price: 20.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:tea,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coffee",
        name_kg: "Кофе",
        name_ru: "Кофе",
        price: 100.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:coffe,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coca-Cola",
        name_kg: "Кока-Кола",
        name_ru: "Кока-Кола",
        promotion:10,
        price: 80,
        gram: 200,
        category: "Juice",
        image:cola,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Tea",
        name_kg: "Чай",
        name_ru: "Чай",
        price: 20.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:tea,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coffee",
        name_kg: "Кофе",
        name_ru: "Кофе",
        price: 100.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:coffe,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coca-Cola",
        name_kg: "Кока-Кола",
        name_ru: "Кока-Кола",
        promotion:10,
        price: 80,
        gram: 200,
        category: "Juice",
        image:cola,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Tea",
        name_kg: "Чай",
        name_ru: "Чай",
        price: 20.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:tea,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coffee",
        name_kg: "Кофе",
        name_ru: "Кофе",
        price: 100.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:coffe,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coca-Cola",
        name_kg: "Кока-Кола",
        name_ru: "Кока-Кола",
        promotion:10,
        price: 80,
        gram: 200,
        category: "Juice",
        image:cola,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Tea",
        name_kg: "Чай",
        name_ru: "Чай",
        price: 20.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:tea,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coffee",
        name_kg: "Кофе",
        name_ru: "Кофе",
        price: 100.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:coffe,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coca-Cola",
        name_kg: "Кока-Кола",
        name_ru: "Кока-Кола",
        promotion:10,
        price: 80,
        gram: 200,
        category: "Juice",
        image:cola,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Tea",
        name_kg: "Чай",
        name_ru: "Чай",
        price: 20.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:tea,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coffee",
        name_kg: "Кофе",
        name_ru: "Кофе",
        price: 100.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:coffe,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coca-Cola",
        name_kg: "Кока-Кола",
        name_ru: "Кока-Кола",
        promotion:10,
        price: 80,
        gram: 200,
        category: "Juice",
        image:cola,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Tea",
        name_kg: "Чай",
        name_ru: "Чай",
        price: 20.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:tea,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coffee",
        name_kg: "Кофе",
        name_ru: "Кофе",
        price: 100.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:coffe,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coca-Cola",
        name_kg: "Кока-Кола",
        name_ru: "Кока-Кола",
        promotion:10,
        price: 80,
        gram: 200,
        category: "Juice",
        image:cola,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Tea",
        name_kg: "Чай",
        name_ru: "Чай",
        price: 20.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:tea,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coffee",
        name_kg: "Кофе",
        name_ru: "Кофе",
        price: 100.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:coffe,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coca-Cola",
        name_kg: "Кока-Кола",
        name_ru: "Кока-Кола",
        promotion:10,
        price: 80,
        gram: 200,
        category: "Juice",
        image:cola,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Tea",
        name_kg: "Чай",
        name_ru: "Чай",
        price: 20.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:tea,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coffee",
        name_kg: "Кофе",
        name_ru: "Кофе",
        price: 100.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:coffe,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coca-Cola",
        name_kg: "Кока-Кола",
        name_ru: "Кока-Кола",
        promotion:10,
        price: 80,
        gram: 200,
        category: "Juice",
        image:cola,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Tea",
        name_kg: "Чай",
        name_ru: "Чай",
        price: 20.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:tea,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coffee",
        name_kg: "Кофе",
        name_ru: "Кофе",
        price: 100.0,
        promotion:20,
        gram: 200,
        category: "Hot",
        image:coffe,
        quantity:1
    },
    {
        id: uniqid(),
        name_en: "Coca-Cola",
        name_kg: "Кока-Кола",
        name_ru: "Кока-Кола",
        promotion:10,
        price: 80,
        gram: 200,
        category: "Juice",
        image:cola,
        quantity:1
    },
]
